name: Deploy to GH Pages

on:
  workflow_dispatch:
  push: { branches: ["main"] }

permissions: { contents: read, pages: write, id-token: write }

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Install xq
        run: |
          repo="sibprogrammer/xq"; base="https://github.com/$repo/releases"
          v="$(curl -Is "$base/latest" | grep '^location')"
          v="${v#*"$repo/releases/tag/v"}"; v="${v%$'\r'}"
          echo "v = $v"
          curl -sfSL "$base/download/v$v/xq_${v}_linux_amd64.tar.gz" | tar xvzf - xq
          sudo mv xq /usr/local/bin
          xq --version
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Pages
        uses: actions/configure-pages@v3
      - name: Generate all image sizes
        run: ./img/make-sizes
      - name: Upload artifacts
        uses: actions/upload-pages-artifact@v2
        with: { path: '.' }
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
