name: Deploy to Production

on:
  workflow_dispatch:
  push: { branches: ["prod"] }

permissions: { contents: read, id-token: write }

concurrency:
  group: "prod"
  cancel-in-progress: false

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Install ncftp and xq
        run: |
          sudo apt install ncftp
          repo="sibprogrammer/xq"; base="https://github.com/$repo/releases"
          v="$(curl -Is "$base/latest" | grep '^location')"
          v="${v#*"$repo/releases/tag/v"}"; v="${v%$'\r'}"
          echo "v = $v"
          curl -sfSL "$base/download/v$v/xq_${v}_linux_amd64.tar.gz" | tar xvzf - xq
          sudo mv xq /usr/local/bin
          xq --version
      - name: Checkout
        uses: actions/checkout@v3
      - name: Generate all image sizes
        run: ./new/img/make-sizes
      - name: Deploy to FTP server
        run: |
          cd new
          ncftpput -u "$FTP_USER" -p "$FTP_PASSWD" -m -T xfer- -R "$FTP_HOST" /new *
        env:
          FTP_HOST:   ${{ secrets.FTP_HOST }}
          FTP_PASSWD: ${{ secrets.FTP_PASSWD }}
          FTP_USER:   ${{ secrets.FTP_USER }}
